### ISSUE TITLE
Request: Picture in Picture

### ISSUE THREAD

**Issue by AlexandraTS** [aws-samples/amazon-ivs-ecommerce-ios-demo#9]
Hello, 
I would like to know if the SDK support picture in picture? 
I want to show the video across all the pages in the App, and show the video even switch to other Apps.

It seems that Apple only support any custom playerLayer which confirm to `AVPlayerLayer`. But the `IVSPlayerLayer` is confirm to `CALayer` instead of `AVPlayerLayer`. (see [Doc](https://developer.apple.com/documentation/avkit/adopting_picture_in_picture_in_a_custom_player))

Thank you.

**Comment by mboulin** [comment]
@AlexandraTS Picture-in-picture, unfortunately, isn't currently supported by the Mobile Player SDK, but this is something the team is actively looking at.
